name: locorda_rdf_core
description: A type-safe, modular Dart library for modeling, encoding, and decoding RDF data.
version: 0.11.6
resolution: workspace
homepage: https://locorda.dev/rdf/core
repository: https://github.com/locorda/rdf
issue_tracker: https://github.com/locorda/rdf/issues
documentation: https://locorda.dev/rdf/core
topics:
  - rdf
  - linked-data
  - semantic-web
  - graph
  - serialization
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  logging: ^1.2.0

dev_dependencies:
  test: ^1.25.0
  yaml: ^3.1.0
  path: ^1.8.0
  lints: ^6.0.0
