name: locorda_rdf_mapper_generator
version: 0.11.0-dev.1
resolution: workspace
homepage: https://locorda.dev/rdf/mapper/generator
repository: https://github.com/locorda/rdf
issue_tracker: https://github.com/locorda/rdf/issues
documentation: https://locorda.dev/rdf/mapper/generator
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"
description: Generate type-safe RDF mappers from annotated Dart classes.

environment:
  sdk: '^3.6.0'
  
dependencies:
  analyzer: '>=7.4.0 <9.0.0'  
  build: '>=2.5.3 <5.0.0'
  dart_style: ">=2.3.7 <4.0.0"
  logging: '>=1.2.0 <2.0.0'
  mustache_template: '>=2.0.0 <3.0.0'
  locorda_rdf_core: ^0.11.0-dev
  locorda_rdf_mapper: ^0.11.0-dev
  locorda_rdf_mapper_annotations: ^0.11.0-dev
  locorda_rdf_terms_core: ^0.11.0-dev
  path: '>=1.9.0 <2.0.0'
  glob: '>=2.0.0 <3.0.0'
  uuid: '>=3.0.0 <5.0.0'

dev_dependencies:
  locorda_rdf_terms_schema: ^0.11.0-dev
  locorda_rdf_terms_common: ^0.11.0-dev
  build_runner: '>=2.5.3 <3.0.0'
  build_test: '>=3.1.0 <4.0.0'
  crypto: '>=3.0.0 <4.0.0'
  lints: ^6.0.0
  test: ^1.25.0
  yaml: '>=3.0.0 <4.0.0'
