name: rdf_mapper_generator
version: 0.10.10-dev
resolution: workspace
homepage: https://kkalass.github.io/rdf_mapper_generator/
repository: https://github.com/kkalass/rdf_mapper_generator
issue_tracker: https://github.com/kkalass/rdf_mapper_generator/issues
documentation: https://kkalass.github.io/rdf_mapper_generator/
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"
description: Generate type-safe RDF mappers from annotated Dart classes.

environment:
  sdk: '^3.6.0'
  
dependencies:
  analyzer: '>=7.4.0 <9.0.0'  
  build: '>=2.5.3 <5.0.0'
  dart_style: ">=2.3.7 <4.0.0"
  logging: '>=1.2.0 <2.0.0'
  mustache_template: '>=2.0.0 <3.0.0'
  rdf_core: ^0.9.20
  rdf_mapper: ^0.10.2
  rdf_mapper_annotations: ^0.10.4
  rdf_vocabularies_core: ^0.4.5
  rdf_vocabularies_schema: ^0.4.5
  path: '>=1.9.0 <2.0.0'
  glob: '>=2.0.0 <3.0.0'
  uuid: '>=3.0.0 <5.0.0'

dev_dependencies:
  build_runner: '>=2.5.3 <3.0.0'
  build_test: '>=3.1.0 <4.0.0'
  crypto: '>=3.0.0 <4.0.0'
  lints: '>=0.1.0 <7.0.0'
  test: '>=1.25.0 <2.0.0'
  yaml: '>=3.0.0 <4.0.0'
