name: locorda_rdf_mapper_annotations
version: 0.11.1
resolution: workspace
homepage: https://locorda.dev/rdf/mapper/annotations
repository: https://github.com/locorda/rdf
issue_tracker: https://github.com/locorda/rdf/issues
documentation: https://locorda.dev/rdf/mapper/annotations
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"
description: >
  Dart annotations for declarative RDF graph mapping and code generation.

environment:
  sdk: '^3.6.0'
dependencies:
  locorda_rdf_core: ^0.11.1
  locorda_rdf_terms_core: ^0.11.1
  locorda_rdf_mapper: ^0.11.1
  logging: ^1.2.0

dev_dependencies:
  test: ^1.25.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  yaml: ^3.1.2
  path: ^1.8.0
  lints: ^6.0.0
  locorda_rdf_terms_common: ^0.11.0-dev
  locorda_rdf_terms_schema: ^0.11.0-dev

