name: locorda_rdf_terms_generator
description: A build_runner for generating type-safe Dart classes from RDF vocabulary namespace IRIs to simplify working with RDF data in Dart.
version: 0.11.1
resolution: workspace
homepage: https://locorda.dev/rdf/terms-generator
repository: https://github.com/locorda/rdf
issue_tracker: https://github.com/locorda/rdf/issues
documentation: https://locorda.dev/rdf/terms-generator
topics:
  - rdf
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"
environment:
  sdk: ^3.7.0
dependencies:
  locorda_rdf_core: ^0.11.1
  locorda_rdf_xml: ^0.11.1
  args: ^2.4.0
  yaml: ^3.1.2
  http: ^1.1.0
  path: ^1.8.0
  build: ">=3.0.0 <5.0.0"
  build_config: ^1.1.1
  build_runner: ^2.10.5
  dart_style: '>=2.3.7 <4.0.0'
  pub_semver: ^2.2.0
  package_config: ^2.2.0
  mustache_template: ^2.0.0
  
executables:
  locorda_rdf_terms_generator:
  
dev_dependencies:
  test: ^1.25.0
  mockito: ^5.4.6
  build_test: ^3.1.0
  coverage: ^1.13.1
  analyzer: ">=7.5.5 <11.0.0" 
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  lints: ^6.0.0

