name: rdf_core
description: A type-safe, modular Dart library for modeling, encoding, and decoding RDF data.
version: 0.9.25-dev
homepage: https://kkalass.github.io/rdf_core/
repository: https://github.com/kkalass/rdf_core
issue_tracker: https://github.com/kkalass/rdf_core/issues
documentation: https://kkalass.github.io/rdf_core/
topics:
  - rdf
  - linked-data
  - semantic-web
  - graph
  - serialization
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.0
  yaml: ^3.1.0
  path: ^1.8.0
  lints: ">=5.1.1 <7.0.0"
