name: rdf_canonicalization
description: A Dart library for RDF graph canonicalization and isomorphism testing, implementing the W3C RDF Dataset Canonicalization specification.
version: 0.2.1-dev
resolution: workspace
homepage: https://kkalass.github.io/rdf_canonicalization/
repository: https://github.com/kkalass/rdf_canonicalization
issue_tracker: https://github.com/kkalass/rdf_canonicalization/issues
documentation: https://kkalass.github.io/rdf_canonicalization/
topics:
  - rdf
  - canonicalization
  - graph-isomorphism
  - semantic-web
  - blank-nodes
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  rdf_core: ^0.9.19
  logging: ^1.3.0

dev_dependencies:
  test: ^1.24.0
  yaml: ^3.1.0
  path: ^1.8.0
  lints: ">=5.1.1 <7.0.0"
